### PR TITLE
Fixed link to Mullvad's config

### PR DESCRIPTION
**Pull request by afoeder**
This essentally removes the `#` from the link so that it works again on the actual web interface of Mullvad's.

### CODE REVIEW

**Comment by DedBash** [comment]
Thanks for the fix, haven't checked the links for ages and didn't really pay attention to them anymore, waiting for Fritz!OS 8 to see if anything changes

**Comment by afoeder** [comment]
sure, that's why we have Open Source :)

out of curiosity: how do you handle IPv6? I kinda decided that I disable v6 on the Fritz!Box entirely and use v4 along with the VPN set to v4.

If I chose to use v6 (on Mullvad's configuration also) I fear that some traffic might leak through IPv4 some DNS resolve to v4. Am I right? wdyt?

**Comment by DedBash** [comment]
Since I am currently still waiting for Deutsche Telekom to expand fiber optics, I am currently using 5G and the IPv6 that I get over it cannot be used by the Fritz!OS. but as I understand it, IPv6 in VPNs will be improved with Fritz!OS 8 (Attention is a German article (https://business.avm.de/de/inhalt/news/2024/fritzos-8-fuer-besseren-ueberblick-und-mehr-komfort/))

**Comment by afoeder** [comment]
interesting, thank you!

**Pull request merged**
